[build]
  command = "chmod +x ./simple_build.sh && ./simple_build.sh"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.35.2"
  NODE_VERSION = "18.17.0"
  SUPABASE_URL = "https://zqcykjxwsnlxmtzcmiga.supabase.co"
  SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpxY3lranh3c25seG10emNtaWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4NDI4MDgsImV4cCI6MjA3MjQxODgwOH0.dkH258TCMv4q7XXLknfnLNCJu1LVqEGdzabsh-0Oj7s"
  APP_NAME = "Graduate Assistant Hub"
  APP_VERSION = "1.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "flutter run -d web-server --web-port 8888"
  port = 8888
  publish = "build/web"