[build]
  command = "./minimal_build.sh"
  publish = "build/web"

[build.environment]
  NODE_VERSION = "18.17.0"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200