[build]
  command = "git clone https://github.com/flutter/flutter.git -b 3.35.2 flutter-sdk && export PATH=\"$PWD/flutter-sdk/bin:$PATH\" && flutter config --enable-web && flutter clean && flutter pub get && flutter build web"
  publish = "build/web"

[build.environment]
  NODE_VERSION = "18.17.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "flutter run -d web-server --web-port 8888"
  port = 8888
  publish = "build/web"