[build]
  command = "chmod +x netlify_build.sh && ./netlify_build.sh"
  publish = "build/web"
  functions = "netlify/functions"

[build.environment]
  FLUTTER_VERSION = "3.24.5"
  NODE_VERSION = "18.19.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "flutter run -d web-server --web-port 8888"
  port = 8888
  publish = "build/web"