name: newly_graduate_hub
description: "A comprehensive mobile app for newly graduated students to build their careers."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  google_fonts: ^6.3.0
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  # record: ^5.0.4  # Temporarily disabled for web build
  # audioplayers: ^5.2.1  # Temporarily disabled for web build
  # permission_handler: ^11.0.1  # Temporarily disabled for web build
  # path_provider: ^2.1.1  # Temporarily disabled for web build
  # shared_preferences: ^2.2.2  # Temporarily disabled for web build
  # connectivity_plus: ^5.0.2  # Temporarily disabled for web build
  lottie: ^3.2.0
  flutter_animate: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  lottie: ^3.2.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/pages_assets/
    - assets/pages_items/
